mining_contract = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.mining-pool"
exchange_contract = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.bridge-contract"
stacks_private_key = "530d9f61984c888536871c6573073bdfc0058896dc1adfe9a6a10dfacadc209101"
bitcoin_private_key = "91436bd90d9cde7ba3162375b7692ae3f22ad01586cb4520bffae48d3a480f6a"
stacks_node_rpc_url = "http://localhost:20443"
bitcoin_node_rpc_url = "http://devnet:devnet@localhost:18443"
transaction_fee = 2000
network = "regtest"
http_relay_url = "http://localhost:9776"
keys_threshold = 4
#frost_state_file = "frost.state.bin"
#network_private_key = "F2BmyfiCuuC7665kwCFw5SgZ8GA6j9wpssn6sqvHBbpX"
#signers =  [
#    {public_key = "xvwd4f8L4oAmAXNhqMvQvbMiniCSeNH1rD9ZwCEEf7b6", key_ids = [1, 2]},
#    {public_key = "cLuu4PSQLxi6bjFYGyTvyAFRUe3XfJL8mQ99Bd9A8mv9", key_ids = [3, 4]},
#    {public_key = "gKCpZS42qdyVh9qQLtjbJYg8reEhjgyho6z6ghmLXZUx", key_ids = [5, 6]}
#]
#coordinator_public_key = "2A1tcY8RFby6pTNk8wQ3qGPCgWRXTL24yMwmcXiG7tKCZ"

# We had these, which worked:
frost_state_file = "frost.state.bin"
network_private_key = "9aSCCR6eirt1NAHwJtSz4HMwBHTyMo62SyPMvVDt5DQn"
signers =  [
    {public_key = "22Rm48xUdpuTuva5gz9S7yDaaw9f8sjMcPSTHYVzPLNcj", key_ids = [1, 2]},
    {public_key = "22Rm48xUdpuTuva5gz9S7yDaaw9f8sjMcPSTHYVzPLNcj", key_ids = [3, 4]},
    {public_key = "22Rm48xUdpuTuva5gz9S7yDaaw9f8sjMcPSTHYVzPLNcj", key_ids = [5, 6]}
]
coordinator_public_key = "22Rm48xUdpuTuva5gz9S7yDaaw9f8sjMcPSTHYVzPLNcj"