sbtc_contract = "SP2BJA4JYFJ7SDMNFJZ9TJ3GB80P9Z80ADPGK1C2F.sbtc-alpha"
stacks_private_key = "7287ba251d44a4d3fd9276c88ce34c5c52a038955511cccaf77e61068649c17801"
stacks_node_rpc_url = "http://localhost:20443"
bitcoin_node_rpc_url = "http://devnet:devnet@localhost:18443"
frost_dkg_round_id = 0
signer_config_path = ""
network_private_key = ""
network = "regtest"
transaction_fee = 2000
